### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [Ghaffaru15/virtual-healthcare#14]
Hi, we appreciate the code, very nice.

Just a question:
This is only API backend for the App, 
there is no web admin interface so I can login, correct?

Another question, how to login in to administrate the backend?

**Comment by ghaffaru** [comment]
Yes. This is only an API.
The web frontend was built by a different developer.

Oauth with Passport was used. there the endpoint `localhost:8000/oauth/token` with `providers: 'admins'` hits the administrator login endpoint.

That is after setting up Passport.
